# GitHub Actions

name: Jupyter Notebook

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 15 5 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: repo
        name: Checkout Repository
        uses: actions/checkout@v3 

      # Installing python and running Jupyter Notebook
      ## Option 1. Using pip
      # - id: python
      #   name: Python Setup & Packages Installation
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.8'
      #     cache: 'pip'
      # - run: pip install -r requirements.txt

      # - id: jupyter
      #   name: Jupyter Notebook Execution
      #   run: |
      #     cd notebooks
      #     jupyter execute solution.ipynb
      #   shell: bash

      ## Option 2. Using pipenv
      - id: python
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - run: |
          pipx install pipenv
          pipenv install

      - id: jupyter
        name: Jupyter Notebook Execution
        run: |
          cd notebooks
          pipenv run jupyter execute solution.ipynb
        shell: bash

      # # Update solution.ipynb file, commit and push
      # - id: commit
      #   name: Commit Results
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add .
      #     git commit -m "Updated solution on $(date) with GitHub Actions"
      #     git push -u origin development
      #   env: 
      #     REPO_KEY: ${{secrets.GITHUB_TOKEN}}
      #     username: github-actions